ST_type: ST
agent_obs_dim: 7
costmap_obs_dim: !!python/tuple
- 1
- 100
- 100
debug: false
ego_state_dim: 6
episode_max_steps: 300
hidden_sizes: !!python/tuple
- 256
- 256
lr: 1.0e-05
max_neighbors: 5
max_obstacles: 5
obs_coord_system: local_goal
obs_hn_dim: 256
obs_type: sa
observation_radius: 5
pi_lr: 1.0e-06
policy_name: Ours
resume: false
retrain: false
rl_algo_name: MultiPPO
robot_circle_num: 10
robot_polygon_num: 0
safe_dist: 0.1
save_interval: 100
save_path: output_dir/debug_R_Ours
seed: 7
sensor_obs_dim: 7
steps_per_epoch: 600
train_epochs: 2000
train_iters: 50
use_gpu: true
v_lr: 1.0e-05
val_test_episodes: 100
world_file: world.yaml
